env:
  browser: true
  es2021: true
  mocha: true
extends: airbnb-base
ignorePatterns:
  - docs/*
overrides:
  - files:
      - "test/*.js"
      - "test/**/*.js"
      - "test/**/**/*.js"
    rules:
      no-console: off
parser: "@babel/eslint-parser"
parserOptions:
  requireConfigFile: false
  babelOptions:
    plugins:
      - '@babel/plugin-syntax-import-assertions'
rules:
  max-len:
    - 1
    - 200
  import/extensions: off
  no-await-in-loop: off